version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/apps/server"
    target-branch: "main"
    commit-message:
      prefix: "chore(deps)"
      prefix-development: "chore(deps)"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "@prisma/client"
        update-types:
          - "version-update:semver-major"
      - dependency-name: "@nestjs/cli"
        update-types:
          - "version-update:semver-major"
      - dependency-name: "@nestjs/common"
        update-types:
          - "version-update:semver-major"
      - dependency-name: "@nestjs/config"
        update-types:
          - "version-update:semver-major"
      - dependency-name: "@nestjs/core"
        update-types:
          - "version-update:semver-major"
      - dependency-name: "@nestjs/platform-express"
        update-types:
          - "version-update:semver-major"
      - dependency-name: "@nestjs/swagger"
        update-types:
          - "version-update:semver-major"
      - dependency-name: "nodemailer"
        update-types:
          - "version-update:semver-major"
      - dependency-name: "prisma"
        update-types:
          - "version-update:semver-major"

  - package-ecosystem: "npm"
    directory: "/apps/web"
    target-branch: "main"
    commit-message:
      prefix: "chore(deps)"
      prefix-development: "chore(deps)"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "@types/react"
        update-types:
          - "version-update:semver-major"
      - dependency-name: "@types/react-dom"
        update-types:
          - "version-update:semver-major"
      - dependency-name: "@vitejs/plugin-react"
        update-types:
          - "version-update:semver-major"
      - dependency-name: "react"
        update-types:
          - "version-update:semver-major"
      - dependency-name: "react-dom"
        update-types:
          - "version-update:semver-major"
      - dependency-name: "typescript"
        update-types:
          - "version-update:semver-major"
      - dependency-name: "vite"
        update-types:
          - "version-update:semver-major"
