version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: taskbandit-postgres
    environment:
      POSTGRES_DB: ${TASKBANDIT_DB_NAME:-taskbandit}
      POSTGRES_USER: ${TASKBANDIT_DB_USER:-taskbandit}
      POSTGRES_PASSWORD: ${TASKBANDIT_DB_PASSWORD:-taskbandit}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  server:
    image: kriziw/taskbandit:${TASKBANDIT_IMAGE_TAG:-latest}
    container_name: taskbandit-server
    environment:
      PORT: 8080
      DATABASE_URL: postgresql://${TASKBANDIT_DB_USER:-taskbandit}:${TASKBANDIT_DB_PASSWORD:-taskbandit}@postgres:5432/${TASKBANDIT_DB_NAME:-taskbandit}?schema=public
      TaskBandit__Auth__Oidc__Authority: ${TASKBANDIT_OIDC_AUTHORITY:-http://authentik.example.local/application/o/taskbandit/}
      TaskBandit__Auth__Oidc__ClientId: ${TASKBANDIT_OIDC_CLIENT_ID:-change-me}
      TaskBandit__Auth__Oidc__ClientSecret: ${TASKBANDIT_OIDC_CLIENT_SECRET:-change-me}
      TASKBANDIT_BOOTSTRAP_SEED_DEMO_DATA: ${TASKBANDIT_BOOTSTRAP_SEED_DEMO_DATA:-true}
      TASKBANDIT_REVERSE_PROXY_ENABLED: ${TASKBANDIT_REVERSE_PROXY_ENABLED:-false}
      TASKBANDIT_REVERSE_PROXY_PATH_BASE: ${TASKBANDIT_REVERSE_PROXY_PATH_BASE:-}
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    pull_policy: always

volumes:
  postgres-data:
